### PR TITLE
Update lesson-plan.md

### PR DESCRIPTION
**Pull request by aleks-hyf**
Example to go thru: movies database as a routing exercise

### CODE REVIEW

**Review by benna100 — APPROVED** [review]
Great, thanks Aleks!

**Comment by benna100** [comment]
Can you make the PR to this repo: https://github.com/HackYourFuture-CPH/node.js

**Comment by aleks-hyf** [comment]
@benna100 i don't know if i have permissions. It just says "Edit file in your fork of the project"

> Can you make the PR to this repo: https://github.com/HackYourFuture-CPH/node.js

**Comment by benna100** [comment]
I have invited you now :)

**Pull request merged**
